module.exports = [
  {
    key: process.env.TOKEN_1,
    discordID: "0",
    nameColor: "#ffffff",
    class: "betatester",
    name: "unnamed#0000",
    note: "note here",
  },
  {
    key: process.env.TOKEN_2,
    discordID: "0",
    nameColor: "#ffffff",
    class: "betatanksforfirend",
    //infiniteLevelUp: true,
    name: "unnamed#0000",
    note: "note here",
  },
  {
    key: process.env.TOKEN_3,
    discordID: "0",
    nameColor: "#bfff00",
    class: "testbedformods",
    infiniteLevelUp: true,
    name: "unnamed#0000",
    note: "note here",
  },
  {
    key: process.env.TOKEN_4,
    discordID: "0",
    nameColor: "#16DC17",
    class: "developer",
    infiniteLevelUp: true,
    ALLOW_SPAM: 1,
    //COLOR: 37,
    name: "unnamed#0000",
    note: "note here",
  },
  {
    key: process.env.TOKEN_5,
    discordID: "0",
    nameColor: "#71fff1",
    class: "betatanksforfirend",
    infiniteLevelUp: false,
    //COLOR: 37,
    name: "unnamed#0000",
    note: "note here",
  },
  {
    key: process.env.BetaTankTokenLol,
    discordID: "0",
    nameColor: "#32CD32",
    class: "betatanksforfirend",
    infiniteLevelUp: false,
    //COLOR: 37,
    name: "unnamed#0000",
    note: "olej",
  },
];
