module.exports = [
  {
    key: process.env.TOKEN_1,
    discordID: "0",
    nameColor: "#ffffff",
    class: "developer",
    infiniteLevelUp: true,
    name: "unnamed#0000",
    note: "note here",
  },
  {
    key: process.env.TOKEN_2,
    discordID: "0",
    nameColor: "#00000",
    class: "betatanksforfirend",
    //infiniteLevelUp: true,
    name: "unnamed#0000",
    note: "note here",
  },
  {
    key: process.env.TOKEN_3,
    discordID: "0",
    nameColor: "#bfff00",
    class: "testbedformods",
    infiniteLevelUp: true,
    name: "unnamed#0000",
    note: "note here",
  },
  {
    key: process.env.TOKEN_4,
    discordID: "0",
    nameColor: "#EE4B2B",
    class: "developer",
    infiniteLevelUp: true,
    //COLOR: 37,
    name: "unnamed#0000",
    note: "note here",
  },
];
